/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package first.java;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author M M Salah
 */
public class APayment extends javax.swing.JFrame {

    /**
     * Creates new form APayment
     */
    public APayment() {
        initComponents();
          setResizable(false);
        try {
            int ID=1;
            String str1=String.valueOf(ID);
            PID.setText(str1);
            Connection con= CONO.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select max(Payment_ID) from payments");
            while(rs.next()){
               ID =rs.getInt(1);
               ID=ID+1;
               String str =String.valueOf(ID);
               PID.setText(str);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PID = new javax.swing.JLabel();
        ADDp = new javax.swing.JButton();
        Viewp = new javax.swing.JButton();
        memname = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        paydate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Payment");

        jPanel1.setBackground(new java.awt.Color(152, 186, 231));

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        jLabel1.setText("Add Payment");

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton1.setText("Back");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Payment ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Member Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Amount");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Payment Date");

        PID.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        PID.setText("000");

        ADDp.setBackground(new java.awt.Color(114, 103, 203));
        ADDp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ADDp.setText("Add");
        ADDp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADDpMouseClicked(evt);
            }
        });

        Viewp.setBackground(new java.awt.Color(114, 103, 203));
        Viewp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Viewp.setText("View Payments");
        Viewp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewpActionPerformed(evt);
            }
        });

        memname.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        memname.setForeground(new java.awt.Color(153, 153, 153));
        memname.setText("Name");
        memname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                memnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                memnameFocusLost(evt);
            }
        });

        amount.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        amount.setForeground(new java.awt.Color(153, 153, 153));
        amount.setText("Amount");
        amount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                amountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                amountFocusLost(evt);
            }
        });
        amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amountKeyTyped(evt);
            }
        });

        paydate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        paydate.setForeground(new java.awt.Color(153, 153, 153));
        paydate.setText("00-00-0000");
        paydate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paydateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                paydateFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ADDp)
                        .addComponent(jLabel5)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memname, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(paydate, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(amount, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Viewp)
                        .addGap(114, 114, 114))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PID))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(memname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(paydate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ADDp, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Viewp, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void memnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_memnameFocusGained
        // TODO add your handling code here:
        if (memname.getText().equals("Name")) {
            memname.setText("");
            memname.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_memnameFocusGained

    private void memnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_memnameFocusLost
        // TODO add your handling code here:
        
        if (memname.getText().equals("")) {
            memname.setText("Name");
            memname.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_memnameFocusLost

    private void paydateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paydateFocusGained
        // TODO add your handling code here:
        if (paydate.getText().equals("00-00-0000")) {
            paydate.setText("");
            paydate.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_paydateFocusGained

    private void paydateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paydateFocusLost
        // TODO add your handling code here:
        if (paydate.getText().equals("")) {
            paydate.setText("00-00-0000");
            paydate.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_paydateFocusLost

    private void amountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amountFocusGained
        // TODO add your handling code here:
        if (amount.getText().equals("Amount")) {
            amount.setText("");
            amount.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_amountFocusGained

    private void amountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amountFocusLost
        // TODO add your handling code here:
        if (amount.getText().equals("")) {
            amount.setText("Amount");
            amount.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_amountFocusLost

    private void ADDpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDpMouseClicked
        // TODO add your handling code here:
        String nam=memname.getText();
        String id=PID.getText();
        
        String am=amount.getText();
        
        String dp=paydate.getText();
        
        try {
            Connection con=CONO.getCon();
        PreparedStatement ps=con.prepareStatement("insert into payments value (?,?,?,?)");
        ps.setString(1, id);
        ps.setString(2, nam);
        ps.setString(3, am);
        ps.setString(4, dp);
        
        ps.executeUpdate();
        JOptionPane.showMessageDialog(null, "Saved Successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_ADDpMouseClicked

    private void amountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_amountKeyTyped

    private void ViewpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewpActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ViewPayments().setVisible(true);
    }//GEN-LAST:event_ViewpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(APayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(APayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(APayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(APayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDp;
    private javax.swing.JLabel PID;
    private javax.swing.JButton Viewp;
    private javax.swing.JTextField amount;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField memname;
    private javax.swing.JTextField paydate;
    // End of variables declaration//GEN-END:variables
}
