/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package first.java;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author M M Salah
 */
public class City_Club extends javax.swing.JFrame {

    /**
     * Creates new form City_Club
     */
    public City_Club() {
        initComponents();
        setBounds(470,225,685,440);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        AdminIDtxt = new javax.swing.JTextField();
        IDIcon = new javax.swing.JLabel();
        PasswordIcon = new javax.swing.JLabel();
        APasswordtxt = new javax.swing.JPasswordField();
        LoginB = new javax.swing.JButton();
        LoginReset = new javax.swing.JButton();
        LoginShowpass = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("City Club");
        setResizable(false);

        jPanel1.setToolTipText("City Club");
        jPanel1.setLayout(null);

        Title.setFont(new java.awt.Font("Sylfaen", 1, 55)); // NOI18N
        Title.setForeground(new java.awt.Color(153, 204, 0));
        Title.setText("City Club");
        jPanel1.add(Title);
        Title.setBounds(183, 46, 304, 73);

        AdminIDtxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        AdminIDtxt.setForeground(new java.awt.Color(153, 153, 153));
        AdminIDtxt.setText("Admin ID");
        AdminIDtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AdminIDtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AdminIDtxtFocusLost(evt);
            }
        });
        AdminIDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminIDtxtActionPerformed(evt);
            }
        });
        AdminIDtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AdminIDtxtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AdminIDtxtKeyTyped(evt);
            }
        });
        jPanel1.add(AdminIDtxt);
        AdminIDtxt.setBounds(205, 158, 180, 34);

        IDIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\m0ham\\Downloads\\icons8-id-verified-24.png")); // NOI18N
        jPanel1.add(IDIcon);
        IDIcon.setBounds(142, 158, 26, 34);

        PasswordIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\m0ham\\Downloads\\icons8-password-24.png")); // NOI18N
        jPanel1.add(PasswordIcon);
        PasswordIcon.setBounds(142, 235, 26, 35);

        APasswordtxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        APasswordtxt.setForeground(new java.awt.Color(153, 153, 153));
        APasswordtxt.setText("Admin Password");
        APasswordtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                APasswordtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                APasswordtxtFocusLost(evt);
            }
        });
        APasswordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APasswordtxtActionPerformed(evt);
            }
        });
        APasswordtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                APasswordtxtKeyPressed(evt);
            }
        });
        jPanel1.add(APasswordtxt);
        APasswordtxt.setBounds(205, 235, 232, 35);

        LoginB.setBackground(new java.awt.Color(51, 204, 255));
        LoginB.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LoginB.setIcon(new javax.swing.ImageIcon("C:\\Users\\m0ham\\Downloads\\icons8-signin-32.png")); // NOI18N
        LoginB.setText("Login");
        LoginB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBActionPerformed(evt);
            }
        });
        jPanel1.add(LoginB);
        LoginB.setBounds(368, 342, 110, 36);

        LoginReset.setBackground(new java.awt.Color(0, 204, 255));
        LoginReset.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LoginReset.setIcon(new javax.swing.ImageIcon("C:\\Users\\m0ham\\Downloads\\icons8-clear-formatting-24.png")); // NOI18N
        LoginReset.setText("Reset");
        LoginReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginResetMouseClicked(evt);
            }
        });
        LoginReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginResetActionPerformed(evt);
            }
        });
        jPanel1.add(LoginReset);
        LoginReset.setBounds(205, 342, 110, 36);

        LoginShowpass.setText("Show Password");
        LoginShowpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginShowpassActionPerformed(evt);
            }
        });
        LoginShowpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginShowpassKeyPressed(evt);
            }
        });
        jPanel1.add(LoginShowpass);
        LoginShowpass.setBounds(455, 244, 120, 21);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\m0ham\\Downloads\\BBB.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-1, 0, 680, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AdminIDtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AdminIDtxtFocusGained

        if (AdminIDtxt.getText().equals("Admin ID")) {
            AdminIDtxt.setText("");
            AdminIDtxt.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_AdminIDtxtFocusGained

    private void AdminIDtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AdminIDtxtFocusLost
        if (AdminIDtxt.getText().equals("")) {
            AdminIDtxt.setText("Admin ID");
            AdminIDtxt.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_AdminIDtxtFocusLost

    private void APasswordtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_APasswordtxtFocusGained
        if (APasswordtxt.getText().equals("Admin Password")) {
            APasswordtxt.setText("");
            APasswordtxt.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_APasswordtxtFocusGained

    private void APasswordtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_APasswordtxtFocusLost
        if (APasswordtxt.getText().equals("")) {
            APasswordtxt.setText("Admin Password");
            APasswordtxt.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_APasswordtxtFocusLost

    private void LoginShowpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginShowpassActionPerformed
        if (LoginShowpass.isSelected()) {
            APasswordtxt.setEchoChar((char)0);
        }
        else
        {
            APasswordtxt.setEchoChar('*');
        }
    }//GEN-LAST:event_LoginShowpassActionPerformed

    private void LoginResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginResetMouseClicked
        AdminIDtxt.setText("");
        APasswordtxt.setText("");
    }//GEN-LAST:event_LoginResetMouseClicked

    private void AdminIDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminIDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminIDtxtActionPerformed

    private void AdminIDtxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AdminIDtxtKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
        
    }//GEN-LAST:event_AdminIDtxtKeyTyped

    private void AdminIDtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AdminIDtxtKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            
                this.dispose();
                new ChooseAction().setVisible(true);
        }
    }//GEN-LAST:event_AdminIDtxtKeyPressed

    private void LoginBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBActionPerformed
       String password=APasswordtxt.getText();
       String username=AdminIDtxt.getText();
       if(password.contains("M123")&&username.contains("94092")||password.contains("A123")&&username.contains("94142")||password.contains("K123")&&username.contains("94244")||password.contains("I123")&&username.contains("94278")||password.contains("B123")&&username.contains("94152"))
       {
           AdminIDtxt.setText(null);
           APasswordtxt.setText(null);
           
           new ChooseAction().setVisible(true);
           this.dispose();
       }else
       {
           JOptionPane.showMessageDialog(null, "You enterd an incorrect Username or password");
       }
        
        
    }//GEN-LAST:event_LoginBActionPerformed

    private void APasswordtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_APasswordtxtKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            
                this.dispose();
                new ChooseAction().setVisible(true);
        }
    }//GEN-LAST:event_APasswordtxtKeyPressed

    private void LoginShowpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginShowpassKeyPressed
                this.dispose();
                new ChooseAction().setVisible(true);
    }//GEN-LAST:event_LoginShowpassKeyPressed

    private void APasswordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APasswordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_APasswordtxtActionPerformed

    private void LoginResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(City_Club.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(City_Club.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(City_Club.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(City_Club.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new City_Club().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField APasswordtxt;
    private javax.swing.JTextField AdminIDtxt;
    private javax.swing.JLabel IDIcon;
    private javax.swing.JButton LoginB;
    private javax.swing.JButton LoginReset;
    private javax.swing.JCheckBox LoginShowpass;
    private javax.swing.JLabel PasswordIcon;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
