/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package first.java;
import  java.sql.*;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author M M Salah
 */
public class NewAdmin extends javax.swing.JFrame {

    /**
     * Creates new form NewAdmin
     */
    public NewAdmin() {
        initComponents();
        setResizable(false);
        try {
            int Job_ID=1;
            String str1=String.valueOf(Job_ID);
            IDJOB.setText(str1);
            Connection con= CONO.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select max(Job_ID) from adminstrative_employees");
            while(rs.next()){
               Job_ID =rs.getInt(1);
               Job_ID=Job_ID+1;
               String str =String.valueOf(Job_ID);
               IDJOB.setText(str);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AName = new javax.swing.JTextField();
        APhone = new javax.swing.JTextField();
        ADOB = new javax.swing.JTextField();
        AEmail = new javax.swing.JTextField();
        ASalary = new javax.swing.JTextField();
        DEP = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        IDJOB = new javax.swing.JLabel();
        ADD = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        GG = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add New Admin");

        jPanel1.setBackground(new java.awt.Color(152, 186, 231));

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        jLabel1.setText("Add New Admin");

        AName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        AName.setForeground(new java.awt.Color(153, 153, 153));
        AName.setText("Name");
        AName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ANameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ANameFocusLost(evt);
            }
        });
        AName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANameActionPerformed(evt);
            }
        });

        APhone.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        APhone.setForeground(new java.awt.Color(153, 153, 153));
        APhone.setText("PhoneNum");
        APhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                APhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                APhoneFocusLost(evt);
            }
        });
        APhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                APhoneKeyTyped(evt);
            }
        });

        ADOB.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ADOB.setForeground(new java.awt.Color(153, 153, 153));
        ADOB.setText("00-00-0000");
        ADOB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ADOBFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ADOBFocusLost(evt);
            }
        });

        AEmail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        AEmail.setForeground(new java.awt.Color(153, 153, 153));
        AEmail.setText("Email");
        AEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AEmailFocusLost(evt);
            }
        });

        ASalary.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ASalary.setForeground(new java.awt.Color(153, 153, 153));
        ASalary.setText("0000");
        ASalary.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ASalaryFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ASalaryFocusLost(evt);
            }
        });
        ASalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ASalaryKeyTyped(evt);
            }
        });

        DEP.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        DEP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IT", "Managment", "Data entry" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Gender");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Job ID");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Department");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Email");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("PhoneNum");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("DOB");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Salary");

        IDJOB.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        IDJOB.setText("000");

        ADD.setBackground(new java.awt.Color(114, 103, 203));
        ADD.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ADD.setText("ADD ");
        ADD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADDMouseClicked(evt);
            }
        });
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });

        Reset.setBackground(new java.awt.Color(114, 103, 203));
        Reset.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        GG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jButton2.setBackground(new java.awt.Color(114, 103, 203));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton2.setText("View Admins");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AName, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDJOB, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DEP, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(110, 110, 110)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(36, 36, 36)
                                .addComponent(APhone, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel2))
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ADOB, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ASalary, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ADD)
                        .addGap(100, 100, 100)
                        .addComponent(Reset)
                        .addGap(112, 112, 112)
                        .addComponent(jButton2)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(APhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(IDJOB))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ADOB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(AName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ASalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(AEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(GG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
       
    }//GEN-LAST:event_ADDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new ChooseAction().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ANameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ANameActionPerformed

    private void ADDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseClicked
        String id=IDJOB.getText();
        String nam=AName.getText();
        String de=(String)DEP.getSelectedItem();
        String mail=AEmail.getText();
        String dob=ADOB.getText();
        String phone=APhone.getText();
        String sal=ASalary.getText();
        String Gen=(String)GG.getSelectedItem();
        try {
            Connection con=CONO.getCon();
        PreparedStatement ps=con.prepareStatement("insert into adminstrative_employees value (?,?,?,?,?,?,?,?)");
        ps.setString(1, id);
        ps.setString(2, nam);
        ps.setString(3, de);
        ps.setString(4, mail);
        ps.setString(5, dob);
        ps.setString(6, phone);
        ps.setString(7, sal);
        ps.setString(8, Gen);
        ps.executeUpdate();
        JOptionPane.showMessageDialog(null, "Saved Successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_ADDMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Admins_inf().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        AName.setText("");
        APhone.setText("");
        AEmail.setText("");
        ADOB.setText("");
        ASalary.setText("");
        
    }//GEN-LAST:event_ResetActionPerformed

    private void ANameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ANameFocusGained
        if (AName.getText().equals("Name")) {
            AName.setText("");
            AName.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_ANameFocusGained

    private void ANameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ANameFocusLost
        if (AName.getText().equals("")) {
            AName.setText("Name");
            AName.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_ANameFocusLost

    private void AEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AEmailFocusGained
        if (AEmail.getText().equals("Email")) {
            AEmail.setText("");
            AEmail.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_AEmailFocusGained

    private void AEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AEmailFocusLost
       if (AEmail.getText().equals("")) {
            AEmail.setText("Email");
            AEmail.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_AEmailFocusLost

    private void APhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_APhoneFocusGained
        if (APhone.getText().equals("PhoneNum")) {
            APhone.setText("");
            APhone.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_APhoneFocusGained

    private void APhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_APhoneFocusLost
        if (APhone.getText().equals("")) {
            APhone.setText("PhoneNum");
            APhone.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_APhoneFocusLost

    private void ADOBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ADOBFocusGained
        if (ADOB.getText().equals("00-00-0000")) {
            ADOB.setText("");
            ADOB.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_ADOBFocusGained

    private void ADOBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ADOBFocusLost
        if (ADOB.getText().equals("")) {
            ADOB.setText("00-00-0000");
            ADOB.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_ADOBFocusLost

    private void ASalaryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ASalaryFocusGained
        if (ASalary.getText().equals("0000")) {
            ASalary.setText("");
            ASalary.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_ASalaryFocusGained

    private void ASalaryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ASalaryFocusLost
        if (ASalary.getText().equals("")) {
            ASalary.setText("0000");
            ASalary.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_ASalaryFocusLost

    private void APhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_APhoneKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_APhoneKeyTyped

    private void ASalaryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ASalaryKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_ASalaryKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JTextField ADOB;
    private javax.swing.JTextField AEmail;
    private javax.swing.JTextField AName;
    private javax.swing.JTextField APhone;
    private javax.swing.JTextField ASalary;
    private javax.swing.JComboBox<String> DEP;
    private javax.swing.JComboBox<String> GG;
    private javax.swing.JLabel IDJOB;
    private javax.swing.JButton Reset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
